import { redirect } from "next/navigation";
import Link from "next/link";
import { currentUser } from "@/lib/clerk";
import { prisma } from "@subletto/db";

function statusBadge(status: string) {
  const map: Record<string, { label: string; classes: string }> = {
    PENDING: { label: "Pending", classes: "bg-slate-100 text-slate-600" },
    GENERATED: { label: "Generated", classes: "bg-blue-100 text-blue-700" },
    SENT_FOR_SIGNATURE: { label: "Awaiting signatures", classes: "bg-amber-100 text-amber-700" },
    SIGNED: { label: "Fully signed", classes: "bg-green-100 text-green-700" },
    DECLINED_SIGNING: { label: "Declined", classes: "bg-red-100 text-red-700" },
  };
  const s = map[status] ?? { label: status, classes: "bg-slate-100 text-slate-600" };
  return (
    <span className={`rounded-full px-2.5 py-0.5 text-xs font-semibold ${s.classes}`}>
      {s.label}
    </span>
  );
}

export default async function DocumentsPage() {
  const clerkUser = await currentUser();
  if (!clerkUser) redirect("/sign-in");

  const user = await prisma.user.findUnique({ where: { clerkId: clerkUser.id } });
  if (!user) redirect("/sign-in");

  const documents = await prisma.document.findMany({
    where: { ownerId: user.id },
    include: {
      match: {
        select: { id: true, listing: { select: { title: true, slug: true } } },
      },
      listing: { select: { id: true, title: true, slug: true } },
    },
    orderBy: { createdAt: "desc" },
  });

  return (
    <main className="mx-auto max-w-3xl px-4 py-10">
      <div className="mb-8 flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-extrabold text-slate-900">Legal Documents</h1>
          <p className="mt-1 text-sm text-slate-500">
            Sublease agreements and landlord approval packets generated by Subletto.
          </p>
        </div>
        {user.role === "LISTER" && (
          <Link
            href="/dashboard/landlord-packet"
            className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-indigo-700"
          >
            Get Landlord Packet →
          </Link>
        )}
      </div>

      {documents.length === 0 ? (
        <div className="rounded-2xl border border-slate-200 bg-white p-10 text-center">
          <span className="text-4xl">📄</span>
          <h2 className="mt-4 text-lg font-bold text-slate-900">No documents yet</h2>
          <p className="mt-2 text-sm text-slate-500">
            Sublease agreements are generated automatically when a match is confirmed. Landlord
            approval packets can be purchased separately.
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {documents.map((doc) => {
            const relatedTitle =
              doc.match?.listing?.title ?? doc.listing?.title ?? "—";
            const matchId = doc.matchId;

            return (
              <div
                key={doc.id}
                className="flex items-center justify-between rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"
              >
                <div className="flex items-center gap-4">
                  <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-50 text-xl">
                    {doc.type === "SUBLEASE_AGREEMENT" ? "📝" : "📬"}
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-slate-900">
                      {doc.type === "SUBLEASE_AGREEMENT"
                        ? "Sublease Agreement"
                        : "Landlord Approval Packet"}
                    </p>
                    <p className="text-xs text-slate-500">{relatedTitle}</p>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  {statusBadge(doc.status)}
                  {matchId && (
                    <Link
                      href={`/dashboard/documents/${matchId}`}
                      className="rounded-lg border border-slate-300 px-3 py-1.5 text-xs font-semibold text-slate-700 hover:bg-slate-50"
                    >
                      View
                    </Link>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </main>
  );
}
